# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d4ba5e74f65550bf79ce65675bcd083b20e3ef91313c904e7b6af36a59f868a2b83d19fca5fda289a6726d918ffd34cbef3e3229b44e3071027a832c458ae128

test:
  secret_key_base: ddf223a5b5f698eba3cec4725ce99ebf3918ed41ed6499b56ac88ad801cf422a9c833b94dcdb4268e01f23cca6eb0c987702a74d40608e39d4e8065d0238fa91

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
